#ifndef TYAPUINTERFACE_GLOBAL_H
#define TYAPUINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TYAPUINTERFACE_LIBRARY)
#  define TYAPUINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TYAPUINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TYAPUINTERFACE_GLOBAL_H
